# Generated by Django 5.2.4 on 2025-08-20 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_populate_basic_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguesequence',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dialoguesequence',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='dialoguesequence',
            name='text',
        ),
        migrations.RemoveField(
            model_name='dialoguesequenceitem',
            name='order',
        ),
        migrations.AddField(
            model_name='dialoguesequenceitem',
            name='index',
            field=models.PositiveIntegerField(default=1, help_text='Orden del diálogo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
