# Generated by Django 5.2.4 on 2025-11-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_populate_basic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='owner_reference',
            field=models.CharField(blank=True, default='Generic', help_text='Texto para organizar UI en Unity.', max_length=50, null=True),
        ),
    ]
