# Generated by Django 5.2.4 on 2025-09-29 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_populate_basic_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponAttackSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('attack_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.attacksequence')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack_sequence1',
            field=models.ManyToManyField(blank=True, related_name='weapons1', through='content.WeaponAttackSequence', to='content.attacksequence'),
        ),
    ]
