# Generated by Django 5.2.4 on 2025-11-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_dialogue_owner_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='trigger_quest_next_step_ids',
            field=models.ManyToManyField(blank=True, related_name='quest_step_ids_to_trigger', to='content.condition'),
        ),
    ]
