# Generated by Django 5.2.4 on 2025-09-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_weaponattacksequence_weapon_attack_sequence1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='attack_sequence',
        ),
    ]
