# Generated by Django 5.2.4 on 2025-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_weapon_attack_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='attack_sequence1',
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack_sequence',
            field=models.ManyToManyField(blank=True, related_name='weapons', through='content.WeaponAttackSequence', to='content.attacksequence'),
        ),
    ]
