# Generated by Django 5.2.4 on 2025-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_weapon_attack_sequence1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='prefab',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='prefab',
        ),
        migrations.AddField(
            model_name='item',
            name='prefab',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
