# Generated by Django 5.2.4 on 2025-09-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_equipment_prefab_remove_weapon_prefab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='prefab',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='prefab',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
