# Generated by Django 5.2.4 on 2025-09-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_equipment_prefab_weapon_prefab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prefab',
            new_name='mesh_path',
        ),
    ]
