# Generated by Django 5.2.4 on 2025-09-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_prefab_item_mesh_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='use_identifier',
            field=models.BooleanField(default=False, help_text='si es True, se usa la Key Al exportar a JSON. Caso contrario se usa identifier.'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('quest_prompt', 'Quest_Prompt'), ('quest_end', 'Quest_End')], max_length=20),
        ),
    ]
